/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `PccRuleODB_RefQosMon`;

DROP TABLE IF EXISTS `PccRuleODB_RefUmN3gData`;

DROP TABLE IF EXISTS `PccRuleODB_RefUmData`;

DROP TABLE IF EXISTS `PccRuleODB_RefChgN3gData`;

DROP TABLE IF EXISTS `PccRuleODB_RefChgData`;

DROP TABLE IF EXISTS `PccRuleODB_RefTcData`;

DROP TABLE IF EXISTS `PccRuleODB_RefAltQosParams`;

DROP TABLE IF EXISTS `PccRuleODB_RefQosData`;

DROP TABLE IF EXISTS `PccRuleODB`;

CREATE TABLE `PccRuleODB` (
  `FlowInfos` TEXT NOT NULL,
  `FlowInfosIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `AppId` TEXT NOT NULL,
  `AppIdIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `AppDescriptor` TEXT NOT NULL,
  `AppDescriptorIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `ContVer` INT NOT NULL DEFAULT 0,
  `ContVerIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `PccRuleId` VARCHAR(128) NOT NULL PRIMARY KEY,
  `Precedence` INT NOT NULL,
  `PrecedenceIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `AfSigProtocol` TEXT NOT NULL,
  `AfSigProtocolIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `AppReloc` TINYINT(1) NOT NULL DEFAULT 0,
  `AppRelocIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `RefQosDataIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `RefAltQosParamsIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `RefTcDataIsSet` TINYINT(1) NOT NULL,
  `RefChgDataIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `RefChgN3gDataIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `RefUmDataIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `RefUmN3gDataIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `RefCondData` TEXT NOT NULL,
  `RefCondDataIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `RefQosMonIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `AddrPreserInd` TINYINT(1) NOT NULL DEFAULT 0,
  `AddrPreserIndIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `TscaiInputDl` TEXT NOT NULL,
  `TscaiInputDlIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `TscaiInputUl` TEXT NOT NULL,
  `TscaiInputUlIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `DdNotifCtrl` TEXT NOT NULL,
  `DdNotifCtrlIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `DdNotifCtrl2` TEXT NOT NULL,
  `DdNotifCtrl2IsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `DisUeNotif` TINYINT(1) NOT NULL DEFAULT 0,
  `DisUeNotifIsSet` TINYINT(1) NOT NULL DEFAULT 0)
 ENGINE=InnoDB;

CREATE TABLE `PccRuleODB_RefQosData` (
  `object_id` VARCHAR(128) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PccRuleODB_RefQosData_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PccRuleODB` (`PccRuleId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PccRuleODB_RefQosData` (`object_id`);

CREATE INDEX `index_i`
  ON `PccRuleODB_RefQosData` (`index`);

CREATE TABLE `PccRuleODB_RefAltQosParams` (
  `object_id` VARCHAR(128) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PccRuleODB_RefAltQosParams_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PccRuleODB` (`PccRuleId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PccRuleODB_RefAltQosParams` (`object_id`);

CREATE INDEX `index_i`
  ON `PccRuleODB_RefAltQosParams` (`index`);

CREATE TABLE `PccRuleODB_RefTcData` (
  `object_id` VARCHAR(128) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PccRuleODB_RefTcData_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PccRuleODB` (`PccRuleId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PccRuleODB_RefTcData` (`object_id`);

CREATE INDEX `index_i`
  ON `PccRuleODB_RefTcData` (`index`);

CREATE TABLE `PccRuleODB_RefChgData` (
  `object_id` VARCHAR(128) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PccRuleODB_RefChgData_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PccRuleODB` (`PccRuleId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PccRuleODB_RefChgData` (`object_id`);

CREATE INDEX `index_i`
  ON `PccRuleODB_RefChgData` (`index`);

CREATE TABLE `PccRuleODB_RefChgN3gData` (
  `object_id` VARCHAR(128) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PccRuleODB_RefChgN3gData_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PccRuleODB` (`PccRuleId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PccRuleODB_RefChgN3gData` (`object_id`);

CREATE INDEX `index_i`
  ON `PccRuleODB_RefChgN3gData` (`index`);

CREATE TABLE `PccRuleODB_RefUmData` (
  `object_id` VARCHAR(128) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PccRuleODB_RefUmData_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PccRuleODB` (`PccRuleId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PccRuleODB_RefUmData` (`object_id`);

CREATE INDEX `index_i`
  ON `PccRuleODB_RefUmData` (`index`);

CREATE TABLE `PccRuleODB_RefUmN3gData` (
  `object_id` VARCHAR(128) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PccRuleODB_RefUmN3gData_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PccRuleODB` (`PccRuleId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PccRuleODB_RefUmN3gData` (`object_id`);

CREATE INDEX `index_i`
  ON `PccRuleODB_RefUmN3gData` (`index`);

CREATE TABLE `PccRuleODB_RefQosMon` (
  `object_id` VARCHAR(128) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PccRuleODB_RefQosMon_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PccRuleODB` (`PccRuleId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PccRuleODB_RefQosMon` (`object_id`);

CREATE INDEX `index_i`
  ON `PccRuleODB_RefQosMon` (`index`);


-- policies\ulcl\pcc_rules\pcc_rules.yaml
-- internet-rule:
--   flowInfos:
--     - flowDescription: permit out ip from any to assigned
--   precedence: 10
--   refTcData:
--     - internet-scenario

-- edge-rule:
--   flowInfos:
--     - flowDescription: permit out ip from any to assigned
--   precedence: 9
--   refTcData:
--     - edge-scenario


-- Insert data for internet-rule
INSERT INTO `PccRuleODB` (
  `FlowInfos`, `FlowInfosIsSet`, `Precedence`, `PrecedenceIsSet`, `PccRuleId`, `RefTcDataIsSet`,
  `AppId`, `AppIdIsSet`, `AppDescriptor`, `AppDescriptorIsSet`, `AfSigProtocol`, `AfSigProtocolIsSet`,
  `RefCondData`, `RefCondDataIsSet`, `TscaiInputDl`, `TscaiInputDlIsSet`, `TscaiInputUl`, `TscaiInputUlIsSet`,
  `DdNotifCtrl`, `DdNotifCtrlIsSet`, `DdNotifCtrl2`, `DdNotifCtrl2IsSet`
) VALUES (
  '[{"flowDescription": "permit out ip from any to assigned"}]', 1, 10, 1, 'internet-rule', 1,
  '', 0, '', 0, '', 0,
  '', 0, '', 0, '', 0,
  '', 0, '', 0
);

-- Insert data for edge-rule
INSERT INTO `PccRuleODB` (
  `FlowInfos`, `FlowInfosIsSet`, `Precedence`, `PrecedenceIsSet`, `PccRuleId`, `RefTcDataIsSet`,
  `AppId`, `AppIdIsSet`, `AppDescriptor`, `AppDescriptorIsSet`, `AfSigProtocol`, `AfSigProtocolIsSet`,
  `RefCondData`, `RefCondDataIsSet`, `TscaiInputDl`, `TscaiInputDlIsSet`, `TscaiInputUl`, `TscaiInputUlIsSet`,
  `DdNotifCtrl`, `DdNotifCtrlIsSet`, `DdNotifCtrl2`, `DdNotifCtrl2IsSet`
) VALUES (
  '[{"flowDescription": "permit out ip from any to assigned"}]', 1, 9, 1, 'edge-rule', 1,
  '', 0, '', 0, '', 0,
  '', 0, '', 0, '', 0,
  '', 0, '', 0
);


INSERT INTO `PccRuleODB_RefTcData` (
  `object_id`, `index`, `value`
) VALUES (
  'internet-rule', 0, 'internet-scenario'
);

INSERT INTO `PccRuleODB_RefTcData` (
  `object_id`, `index`, `value`
) VALUES (
  'edge-rule', 0, 'edge-scenario'
);
