/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `TrafficControlDataODB`;

CREATE TABLE `TrafficControlDataODB` (
  `TcId` VARCHAR(128) NOT NULL PRIMARY KEY,
  `FlowStatus` TEXT NOT NULL,
  `FlowStatusIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `RedirectInfo` TEXT NOT NULL,
  `RedirectInfoIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `AddRedirectInfo` TEXT NOT NULL,
  `AddRedirectInfoIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `MuteNotif` TINYINT(1) NOT NULL DEFAULT 0,
  `MuteNotifIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `TrafficSteeringPolIdDl` TEXT NOT NULL,
  `TrafficSteeringPolIdDlIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `TrafficSteeringPolIdUl` TEXT NOT NULL,
  `TrafficSteeringPolIdUlIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `RouteToLocs` TEXT NOT NULL,
  `RouteToLocsIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `TraffCorreInd` TINYINT(1) NOT NULL DEFAULT 0,
  `TraffCorreIndIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `UpPathChgEvent` TEXT NOT NULL,
  `UpPathChgEventIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `SteerFun` TEXT NOT NULL,
  `SteerFunIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `SteerModeDl` TEXT NOT NULL,
  `SteerModeDlIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `SteerModeUl` TEXT NOT NULL,
  `SteerModeUlIsSet` TINYINT(1) NOT NULL DEFAULT 0,
  `MulAccCtrl` TEXT NOT NULL,
  `MulAccCtrlIsSet` TINYINT(1) NOT NULL DEFAULT 0)
 ENGINE=InnoDB;

-- based on policies\ulcl\traffic_rules\traffic_rule.yaml
-- edge-scenario:
--   routeToLocs:
--   - dnai: access 
--   - dnai: ulcl
--   - dnai: aupf2
--   - dnai: edge

-- internet-scenario:
--   routeToLocs:
--     - dnai: access
--     - dnai: ulcl
--     - dnai: aupf1
--     - dnai: internet

-- Insert into TrafficControlDataODB table for edge-scenario
INSERT INTO `TrafficControlDataODB` (
  `TcId`, `FlowStatus`, `FlowStatusIsSet`, `RedirectInfo`, `RedirectInfoIsSet`, `AddRedirectInfo`, `AddRedirectInfoIsSet`,
  `MuteNotif`, `MuteNotifIsSet`, `TrafficSteeringPolIdDl`, `TrafficSteeringPolIdDlIsSet`, `TrafficSteeringPolIdUl`, `TrafficSteeringPolIdUlIsSet`,
  `RouteToLocs`, `RouteToLocsIsSet`, `TraffCorreInd`, `TraffCorreIndIsSet`, `UpPathChgEvent`, `UpPathChgEventIsSet`,
  `SteerFun`, `SteerFunIsSet`, `SteerModeDl`, `SteerModeDlIsSet`, `SteerModeUl`, `SteerModeUlIsSet`, `MulAccCtrl`, `MulAccCtrlIsSet`
) VALUES (
  'edge-scenario', '', 0, '', 0, '', 0,
  0, 0, '', 0, '', 0,
  '[{"dnai": "access"}, {"dnai": "ulcl"}, {"dnai": "aupf2"}, {"dnai": "edge"}]', 1, 0, 0, '', 0,
  '', 0, '', 0, '', 0, '', 0
);

-- Insert into TrafficControlDataODB table for internet-scenario
INSERT INTO `TrafficControlDataODB` (
  `TcId`, `FlowStatus`, `FlowStatusIsSet`, `RedirectInfo`, `RedirectInfoIsSet`, `AddRedirectInfo`, `AddRedirectInfoIsSet`,
  `MuteNotif`, `MuteNotifIsSet`, `TrafficSteeringPolIdDl`, `TrafficSteeringPolIdDlIsSet`, `TrafficSteeringPolIdUl`, `TrafficSteeringPolIdUlIsSet`,
  `RouteToLocs`, `RouteToLocsIsSet`, `TraffCorreInd`, `TraffCorreIndIsSet`, `UpPathChgEvent`, `UpPathChgEventIsSet`,
  `SteerFun`, `SteerFunIsSet`, `SteerModeDl`, `SteerModeDlIsSet`, `SteerModeUl`, `SteerModeUlIsSet`, `MulAccCtrl`, `MulAccCtrlIsSet`
) VALUES (
  'internet-scenario', '', 0, '', 0, '', 0,
  0, 0, '', 0, '', 0,
  '[{"dnai": "access"}, {"dnai": "ulcl"}, {"dnai": "aupf1"}, {"dnai": "internet"}]', 1, 0, 0, '', 0,
  '', 0, '', 0, '', 0, '', 0
);
